---

all:
  hosts:
    samsung.lan:
      packages_install:
        - powertop
    xps.lan:
      packages_install:
        - git
        - acpi
        - dell-bios-fan-control
        - i8kutils
        - lm_sensors
        - powertop
        - toolbox
        - xclip
      tailscale_accept_routes: true
