---

all:
  hosts:
    samsung.lan:
      vars:
        packages_install:
          - powertop
    xps.lan:
      vars:
        packages_install:
          - git
          - acpi
          - dell-bios-fan-control
          - i8kutils
          - lm_sensors
          - powertop
        tailscale_accept_routes: true
