---

- name: Configure COPR repository
  ansible.builtin.get_url:
    url: https://copr.fedorainfracloud.org/coprs/fossrob/epel9/repo/fedora-37/fossrob-epel9-fedora-37.repo
    dest: /etc/yum.repos.d/
    owner: root
    group: root
    mode: 0644
  become: true

- name: Refresh rpm-ostree metadata
  ansible.builtin.command:
    cmd: rpm-ostree refresh-md
  changed_when: false
  become: true

- name: Install packages
  ansible.builtin.command:
    cmd: rpm-ostree install --idempotent --apply-live {{ packages | join(' ') }}
  vars:
    packages:
      - acpi
      - dell-bios-fan-control
      - i8kutils
  changed_when: false
  become: true

- name: Enable and start i8kmon service
  ansible.builtin.systemd:
    name: i8kmon.service
    enabled: true
    state: started
  become: true
