---

- name: Disable suspend on lid closing
  ansible.builtin.replace:
    path: /etc/systemd/logind.conf
    regexp: '^[#]?(HandleLidSwitch.*)=(.*$)'
    replace: '\1=ignore'
  notify: restart systemd-logind
  become: true
