---

- name: Gather minimal facts
  ansible.builtin.setup:
    gather_subset:
      - distribution
      - pkg_mgr

- name: Include tasks based on distribution
  ansible.builtin.include_tasks:
    file: "{{ ansible_distribution | lower }}-{{ ansible_pkg_mgr }}.yml"
