---
- name: Add Flatpak remote for Flathub
  community.general.flatpak_remote:
    name: flathub
    flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo
    state: present
  become: true

- name: Ensure no filter for Flathub remote
  ansible.builtin.command:
    cmd: flatpak remote-modify flathub --no-filter
  changed_when: false
  become: true

- name: Install Flatpak runtimes
  community.general.flatpak:
    name:
      - org.gtk.Gtk3theme.Adwaita-dark
      - runtime/org.freedesktop.Platform.ffmpeg-full/x86_64/22.08
    state: present
  changed_when: false
  become: true

- name: Fetch list of installed apps
  ansible.builtin.shell:
    cmd: flatpak list --app --columns=application | tail -n +1
  changed_when: false
  register: flatpaks_installed
  when: flatpaks_purge

- name: Remove unwanted Flatpak apps
  community.general.flatpak:
    name: "{{ flatpaks_installed.stdout_lines | difference(flatpaks_install) }}"
    state: absent
  when: flatpaks_purge
  become: true

- name: Install Flatpak apps
  community.general.flatpak:
    name: "{{ flatpaks_install }}"
    state: present
  become: true

- name: Configure dark theme
  ansible.builtin.command:
    cmd: flatpak override --env=GTK_THEME=Adwaita-dark
  changed_when: false
  become: true
